name: 'CSV to PSV'
author: Mohan Chinnappan
description: 'This action converts a given CSV file PSV (pipe separated value)'
inputs:
  input-csv-file:
    description: Input CSV file to convert into PSV
    required: true
    default: "input.csv"
  num:
    description: 'Enter a number'
    required: true
    default: "1"
    
outputs:
  num_squared:
    description: 'Square of the input'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-square.outputs.num_squared }}
    
    
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Pass Inputs to Shell
      run: |
              echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the number's square
      id: get-square
      run: python src/get_num_square.py
      shell: bash
      
      
branding:
  icon: 'terminal'  
  color: 'purple'
